export {
  backfillSessionFiles,
  indexSessionFile,
  isRawChatIndexingEnabled,
  resolveSessionAgentIdFromKey,
  startRawChatIndexer,
  stopRawChatIndexer,
  // RAW_CHAT_SEARCH Phase 2: pair embedding indexer & backfill
  embedPendingPairs,
  backfillEmbeddings,
  startEmbeddingBackfill,
  scheduleEmbeddingSweep,
  extractConversationPairs,
  formatPairText,
  formatPairSnippet,
  isNoiseTurn,
  PAIR_SNIPPET_MAX_LENGTH,
  type EmbedPendingOptions,
  type EmbedPendingResult,
  type BackfillEmbeddingsOptions,
  type BackfillEmbeddingsResult,
  type RawChatIndexerOptions,
  type ExtractedPair,
} from "../../../extensions/raw-chat-search/index.js";
